version: 1

services:
  - name: gsite
    buildCommand: npm install && npm build
    startCommand: node server/index.js
    env:
      NODE_ENV: production
    routes:
      - path: /gericka
        methods: ["POST"]
        internal: true
